version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/UI/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "7900:80"
      - "44312:443"
    depends_on: 
      - db
  db:
      image: microsoft/mssql-server-linux:latest
      ports:
          - "1433:1433"
      environment:
          - ACCEPT_EULA=Y
          - MSSQL_PID=Express
          - SA_PASSWORD=Password123
      expose:
          - "1433"     
  app:
      image: clientapp
      build: 
        context: .
        dockerfile: src/UI/Web/Client/Dockerfile
      ports:
      - "5001:80"
      - "5000:443"
        
networks:
  default:
    external:
      name: nat